---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Rao xiao'yan.
--- DateTime: 2020/2/24 16:21
---
local utils = require 'kong.plugins.canary';
local cjson = require "cjson"
local cmatch = require 'kong.plugins.canary.policies.cmatch';
local BaseCanary = require 'kong.plugins.canary.policies.BaseCanary';

local policy = "uid";

local UidCanary = BaseCanary:new();

function UidCanary:new(o, conf)
  o = o or BaseCanary:new(o, policy, conf)
  setmetatable(o, self);
  self.__index = self;
  return o;
end

function UidCanary:validate()
  if not self.conf.uid.name or not self.conf.uid.range or #self.conf.uid.range == 0 then
    return true, nil;
  end
  local values = utils[self.conf.uid.on].getValue(self.conf.uid.name);
  kong.log.notice('conf.name:', self.conf.uid.name, ',value:', cjson.encode(values))
  if type(values) == 'string' then
    if cmatch.match(self.conf.uid.range, values) then
      return true, self.name;
    end
  elseif type(values) == 'table' then
    for _, v in ipairs(values) do
      if cmatch.match(self.conf.uid.range, v) then
        return true, self.name;
      end
    end
  end
  return false, self.name;
end

function UidCanary:get_upstream()
  return self.conf.uid.upstream;
end

return UidCanary;
