---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/2/24 17:33
---
return {
  ['header'] = {
    getValue = function(name)
      return kong.request.get_header(name);
    end
  },
  ['cookie'] = {
    getValue = function(name)
      return ngx.var["cookie_" .. name];
    end
  },
  ['args'] = {
    getValue = function(name)
      for k, v in pairs(kong.request.get_query()) do
        if k == name then
          return v;
        end
      end
    end
  }
}
